name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"

    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        uv --version

    - name: Create virtual environment and install dependencies
      run: |
        uv venv
        source .venv/bin/activate
        uv pip install ".[dev]"

    - name: Run tests with coverage
      run: |
        source .venv/bin/activate
        python -m pytest --cov=src --cov-report=term-missing --cov-report=xml --cov-fail-under=95

    - name: Coveralls workflow
      uses: coverallsapp/github-action@v2
      env:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file: coverage.xml
